import type { Metadata } from "next";
import { Secular_One, Didact_Gothic } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const secularOne = Secular_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-secular-one",
});

const didactGothic = Didact_Gothic({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-didact-gothic",
});

export const metadata: Metadata = {
  title: "Andalus - Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        {/* Favicon */}
        <link rel="icon" href="/favicon.png" />
        {/* Apple Touch Icon */}
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
      </Head>
      <body className={`${secularOne.variable} ${didactGothic.variable}`}>
        {children}
      </body>
    </html>
  );
}
